# Generated by Django 3.1.3 on 2022-09-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Имя покепона на русском')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Имя покепона на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Имя покепона на японском')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционирует')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(null=True, verbose_name='Появляется')),
                ('disappeared_at', models.DateTimeField(null=True, verbose_name='Исчезает')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('health', models.IntegerField(verbose_name='Здоровье')),
                ('strength', models.IntegerField(verbose_name='Атака')),
                ('defence', models.IntegerField(verbose_name='Защита')),
                ('stamina', models.IntegerField(verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
